// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamEUJwi6jbi7rOS7qCCLMguJin2QNnrY',
    appId: '1:800045136414:web:da2c4a12069933c08c4c0f',
    messagingSenderId: '800045136414',
    projectId: 'multi-store-app-574df',
    authDomain: 'multi-store-app-574df.firebaseapp.com',
    storageBucket: 'multi-store-app-574df.appspot.com',
    measurementId: 'G-GPNBF5YSD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJa0e3YEThuZQqhsGOYpvgOPHgH6aCk5M',
    appId: '1:800045136414:android:92aa9fffbfd163818c4c0f',
    messagingSenderId: '800045136414',
    projectId: 'multi-store-app-574df',
    storageBucket: 'multi-store-app-574df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPq05dORsg7-mK265KNWDSibDaPl_00Uc',
    appId: '1:800045136414:ios:172353ea1d85c23d8c4c0f',
    messagingSenderId: '800045136414',
    projectId: 'multi-store-app-574df',
    storageBucket: 'multi-store-app-574df.appspot.com',
    iosClientId: '800045136414-v8qvnph3utp52hscr8gpj0hhduf5aijr.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStoreApp',
  );
}
